### ISSUE TITLE
请问seg文件哪里可以下载？或者可以给我一份吗

### ISSUE THREAD

**Issue by zwb195** [hello-sea/DeepLearning_Wavelet-LSTM#3]
请问seg文件哪里可以下载？
或者可以给我一份吗 330863024@qq.com  多谢

**Comment by hello-sea** [comment]
Hello, for your convenience, I will provide a generic API for handling different types of digital signals.
您好，为了方便大家使用，我将提供处理不同类型数字信号的通用API。

**Comment by chenchen1112** [comment]
seg文件？
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Sea"<notifications@github.com>;
 发送时间: 2019年8月30日(星期五) 下午4:21
 收件人: "hello-sea/DeepLearning_Wavelet-LSTM"<DeepLearning_Wavelet-LSTM@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: Re: [hello-sea/DeepLearning_Wavelet-LSTM] 请问seg文件哪里可以下载？或者可以给我一份吗 (#3)

 

 
Hello, for your convenience, I will provide a generic API for handling different types of digital signals.
您好，为了方便大家使用，我将提供处理不同类型数字信号的通用API。
