### ISSUE TITLE
指教

### ISSUE THREAD

**Issue by chengming66** [hello-sea/DeepLearning_Wavelet-LSTM#4]
您好，请问可以提供一个联系方式么，我想具体请教一下

**Comment by hello-sea** [comment]
Hello, the specific content is recommended to be discussed here.My email address is hello.sea@qq.com
您好，具体内容建议在这里讨论。我的邮箱是hello.sea@qq.com

**Comment by chenchen1112** [comment]
抱歉，能具体讲讲要请教的是什么吗？我现在有点云里雾里

 

 ------------------ 原始邮件 ------------------
  发件人: "chengming66"<notifications@github.com>;
 发送时间: 2019年8月26日(星期一) 晚上6:44
 收件人: "hello-sea/DeepLearning_Wavelet-LSTM"<DeepLearning_Wavelet-LSTM@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: [hello-sea/DeepLearning_Wavelet-LSTM] 指教 (#4)

 

 
您好，请问可以提供一个联系方式么，我想具体请教一下

**Comment by chengming66** [comment]
您好，可以加个联系方式么  QQ 976827675




------------------ 原始邮件 ------------------
发件人: "chenchen1112"<notifications@github.com>;
发送时间: 2019年9月4日(星期三) 下午2:30
收件人: "hello-sea/DeepLearning_Wavelet-LSTM"<DeepLearning_Wavelet-LSTM@noreply.github.com>;
抄送: "程铭"<976827675@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hello-sea/DeepLearning_Wavelet-LSTM] 指教 (#4)



抱歉，能具体讲讲要请教的是什么吗？我现在有点云里雾里 
 
   
 
  ------------------ 原始邮件 ------------------ 
   发件人: "chengming66"<notifications@github.com>; 
  发送时间: 2019年8月26日(星期一) 晚上6:44 
  收件人: "hello-sea/DeepLearning_Wavelet-LSTM"<DeepLearning_Wavelet-LSTM@noreply.github.com>; 
  抄送: "Subscribed"<subscribed@noreply.github.com>; 
  主题: [hello-sea/DeepLearning_Wavelet-LSTM] 指教 (#4) 
 
   
 
   
 您好，请问可以提供一个联系方式么，我想具体请教一下
